name: Send Matrix Message

on:
  schedule:
    - cron: '*/5 * * * *'  # Every Tuesday at 08:00 UTC '0 8 * * 2'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run message script
        env:
          MATRIX_USERNAME: ${{ secrets.MATRIX_USERNAME }}
          MATRIX_TOKEN: ${{ secrets.MATRIX_TOKEN }}
          MATRIX_ROOM_ID: ${{ secrets.MATRIX_ROOM_ID }}
        run: |
          python src/roleapp.py
